<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 TRANSITIONAL//EN">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>Fedora Server Installation</title>
    <link
      rel="stylesheet"
      type="text/css"
      media="screen,print"
      href="/stylesheets/Welcome./css/fedora_install.css"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="/stylesheets/install./css/fedora_install.css"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="./install./css/fedora_install.css"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="../install./css/fedora_install.css"
    />
    <meta status="incomplete" />
  </head>
  <body>
    <h2><a>Default</a></h2>

    <!-- PRINTING STARTS HERE -->
    <div class="content">
      <h1>Java - Exceptions Handling</h1>
      <div class="topgooglead">
        <div style="padding-bottom: 5px; padding-left: 10px">
          Advertisements
        </div>
        <script type="text/javascript">
          <!--
          google_ad_client = "pub-7133395778201029";
          google_ad_width = 468;
          google_ad_height = 60;
          google_ad_format = "468x60_as";
          google_ad_type = "image";
          google_ad_channel = "";
          //-->
        </script>
        <script
          type="text/javascript"
          src="http://pagead2.googlesyndication.com/pagead/show_ads.js"
        ></script>
      </div>
      <hr />
      <div class="pre-btn">
        <a href="/java/java_files_io.htm">Previous Page</a>
      </div>
      <div class="nxt-btn">
        <a href="/java/java_inheritance.htm">Next Page</a>
      </div>
      <div class="clearer"></div>
      <hr />
      <p>
        An exception is a problem that arises during the execution of a program.
        An exception can occur for many different reasons, including the
        following:
      </p>
      <ul class="list">
        <li><p>A user has entered invalid data.</p></li>
        <li><p>A file that needs to be opened cannot be found.</p></li>
        <li>
          <p>
            A network connection has been lost in the middle of communications,
            or the JVM has run out of memory.
          </p>
        </li>
      </ul>
      <p>
        Some of these exceptions are caused by user error, others by programmer
        error, and others by physical resources that have failed in some manner.
      </p>
      <p>
        To understand how exception handling works in Java, you need to
        understand the three categories of exceptions:
      </p>
      <ul class="list">
        <li>
          <p>
            <b>Checked exceptions:</b> A checked exception is an exception that
            is typically a user error or a problem that cannot be foreseen by
            the programmer. For example, if a file is to be opened, but the file
            cannot be found, an exception occurs. These exceptions cannot simply
            be ignored at the time of compilation.
          </p>
        </li>
        <li>
          <p>
            <b>Runtime exceptions:</b> A runtime exception is an exception that
            occurs that probably could have been avoided by the programmer. As
            opposed to checked exceptions, runtime exceptions are ignored at the
            time of compliation.
          </p>
        </li>
        <li>
          <p>
            <b>Errors:</b> These are not exceptions at all, but problems that
            arise beyond the control of the user or the programmer. Errors are
            typically ignored in your code because you can rarely do anything
            about an error. For example, if a stack overflow occurs, an error
            will arise. They are also ignored at the time of compilation.
          </p>
        </li>
      </ul>
      <h2>Exception Hierarchy:</h2>
      <p>
        All exception classes are subtypes of the java.lang.Exception class. The
        exception class is a subclass of the Throwable class. Other than the
        exception class there is another subclass called Error which is derived
        from the Throwable class.
      </p>
      <p>
        Errors are not normally trapped form the Java programs. These conditions
        normally happen in case of severe failures, which are not handled by the
        java programs. Errors are generated to indicate errors generated by the
        runtime environment. Example : JVM is out of Memory. Normally programs
        cannot recover from errors.
      </p>
      <p>
        The Exception class has two main subclasses : IOException class and
        RuntimeException Class.
      </p>
      <center>
        <img src="/images/exceptions.jpg" alt="Java Exceptions" />
      </center>
      <p>
        Here is a list of most common checked and unchecked
        <a href="/java/java_builtin_exceptions.htm"
          >Java's Built-in Exceptions</a
        >.
      </p>
      <h2>Exceptions Methods:</h2>
      <p>
        Following is the list of important medthods available in the Throwable
        class.
      </p>
      <table class="src">
        <tr>
          <th>SN</th>
          <th>Methods with Description</th>
        </tr>
        <tr>
          <td>1</td>
          <td>
            <b>public String getMessage()</b><br />Returns a detailed message
            about the exception that has occurred. This message is initialized
            in the Throwable constructor.
          </td>
        </tr>
        <tr>
          <td>2</td>
          <td>
            <b>public Throwable getCause()</b><br />Returns the cause of the
            exception as represented by a Throwable object.
          </td>
        </tr>
        <tr>
          <td>3</td>
          <td>
            <b>public String toString()</b><br />Returns the name of the class
            concatenated with the result of getMessage()
          </td>
        </tr>
        <tr>
          <td>4</td>
          <td>
            <b>public void printStackTrace()</b><br />Prints the result of
            toString() along with the stack trace to System.err, the error
            output stream.
          </td>
        </tr>
        <tr>
          <td>5</td>
          <td>
            <b>public StackTraceElement [] getStackTrace()</b><br />Returns an
            array containing each element on the stack trace. The element at
            index 0 represents the top of the call stack, and the last element
            in the array represents the method at the bottom of the call stack.
          </td>
        </tr>
        <tr>
          <td>6</td>
          <td>
            <b>public Throwable fillInStackTrace()</b><br />Fills the stack
            trace of this Throwable object with the current stack trace, adding
            to any previous information in the stack trace.
          </td>
        </tr>
      </table>
      <h2>Catching Exceptions:</h2>
      <p>
        A method catches an exception using a combination of the <b>try</b> and
        <b>catch</b> keywords. A try/catch block is placed around the code that
        might generate an exception. Code within a try/catch block is referred
        to as protected code, and the syntax for using try/catch looks like the
        following:
      </p>
      <pre class="prettyprint">
try
{
   //Protected code
}catch(ExceptionName e1)
{
   //Catch block
}
</pre
      >
      <p>
        A catch statement involves declaring the type of exception you are
        trying to catch. If an exception occurs in protected code, the catch
        block (or blocks) that follows the try is checked. If the type of
        exception that occurred is listed in a catch block, the exception is
        passed to the catch block much as an argument is passed into a method
        parameter.
      </p>
      <h2>Example:</h2>
      <p>
        The following is an array is declared with 2 elements. Then the code
        tries to access the 3rd element of the array which throws an exception.
      </p>
      <pre class="prettyprint">
// File Name : ExcepTest.java
import java.io.*;
public class ExcepTest{

   public static void main(String args[]){
      try{
         int a[] = new int[2];
         System.out.println("Access element three :" + a[3]);
      }catch(ArrayIndexOutOfBoundsException e){
         System.out.println("Exception thrown  :" + e);
      }
      System.out.println("Out of the block");
   }
}
</pre
      >
      <p>This would produce following result:</p>
      <pre class="prettyprint">
Exception thrown  :java.lang.ArrayIndexOutOfBoundsException: 3
Out of the block
</pre
      >
      <h2>Multiple catch Blocks:</h2>
      <p>
        A try block can be followed by multiple catch blocks. The syntax for
        multiple catch blocks looks like the following:
      </p>
      <pre class="prettyprint">
try
{
   //Protected code
}catch(ExceptionType1 e1)
{
   //Catch block
}catch(ExceptionType2 e2)
{
   //Catch block
}catch(ExceptionType3 e3)
{
   //Catch block
}
</pre
      >
      <p>
        The previous statements demonstrate three catch blocks, but you can have
        any number of them after a single try. If an exception occurs in the
        protected code, the exception is thrown to the first catch block in the
        list. If the data type of the exception thrown matches ExceptionType1,
        it gets caught there. If not, the exception passes down to the second
        catch statement. This continues until the exception either is caught or
        falls through all catches, in which case the current method stops
        execution and the exception is thrown down to the previous method on the
        call stack.
      </p>
      <h2>Example:</h2>
      <p>
        Here is code segment showing how to use multiple try/catch statements.
      </p>
      <pre class="prettyprint">
try
{
   file = new FileInputStream(fileName);
   x = (byte) file.read();
}catch(IOException i)
{
   i.printStackTrace();
   return -1;
}catch(FileNotFoundException f) //Not valid!
{
   f.printStackTrace();
   return -1;
}
</pre
      >
      <h2>The throws/throw Keywords:</h2>
      <p>
        If a method does not handle a checked exception, the method must declare
        it using the <b>throws</b> keyword. The throws keyword appears at the
        end of a method's signature.
      </p>
      <p>
        You can throw an exception, either a newly instantiated one or an
        exception that you just caught, by using the <b>throw</b> keyword. Try
        to understand the different in throws and throw keywords.
      </p>
      <p>The following method declares that it throws a RemoteException:</p>
      <pre class="prettyprint">
import java.io.*;
public class className
{
   public void deposit(double amount) throws RemoteException
   {
      // Method implementation
      throw new RemoteException();
   }
   //Remainder of class definition
}
</pre
      >
      <p>
        A method can declare that it throws more than one exception, in which
        case the exceptions are declared in a list separated by commas. For
        example, the following method declares that it throws a RemoteException
        and an InsufficientFundsException:
      </p>
      <pre class="prettyprint">
import java.io.*;
public class className
{
   public void withdraw(double amount) throws RemoteException,
                              InsufficientFundsException
   {
       // Method implementation
   }
   //Remainder of class definition
}
</pre
      >
      <h2>The finally Keyword</h2>
      <p>
        The finally keyword is used to create a block of code that follows a try
        block. A finally block of code always executes, whether or not an
        exception has occurred.
      </p>
      <p>
        Using a finally block allows you to run any cleanup-type statements that
        you want to execute, no matter what happens in the protected code.
      </p>
      <p>
        A finally block appears at the end of the catch blocks and has the
        following syntax:
      </p>
      <pre class="prettyprint">
try
{
   //Protected code
}catch(ExceptionType1 e1)
{
   //Catch block
}catch(ExceptionType2 e2)
{
   //Catch block
}catch(ExceptionType3 e3)
{
   //Catch block
}finally
{
   //The finally block always executes.
}
</pre
      >
      <h2>Example:</h2>
      <pre class="prettyprint">
public class ExcepTest{

   public static void main(String args[]){
      int a[] = new int[2];
      try{
         System.out.println("Access element three :" + a[3]);
      }catch(ArrayIndexOutOfBoundsException e){
         System.out.println("Exception thrown  :" + e);
      }
      finally{
         a[0] = 6;
         System.out.println("First element value: " +a[0]);
         System.out.println("The finally statement is executed");
      }
   }
}
</pre
      >
      <p>This would produce following result:</p>
      <pre class="prettyprint">
Exception thrown  :java.lang.ArrayIndexOutOfBoundsException: 3
First element value: 6
The finally statement is executed
</pre
      >
      <p>Note the following:</p>
      <ul class="list">
        <li><p>A catch clause cannot exist without a try statement.</p></li>
        <li>
          <p>
            It is not compulsory to have finally clauses when ever a try/catch
            block is present.
          </p>
        </li>
        <li>
          <p>
            The try block cannot be present without either catch clause or
            finally clause.
          </p>
        </li>
        <li>
          <p>
            Any code cannot be present in between the try, catch, finally
            blocks.
          </p>
        </li>
      </ul>
      <h2>Declaring you own Exception:</h2>
      <p>
        You can create your own exceptions in Java. Keep the following points in
        mind when writing your own exception classes:
      </p>
      <ul class="list">
        <li><p>All exceptions must be a child of Throwable.</p></li>
        <li>
          <p>
            If you want to write a checked exception that is automatically
            enforced by the Handle or Declare Rule, you need to extend the
            Exception class.
          </p>
        </li>
        <li>
          <p>
            If you want to write a runtime exception, you need to extend the
            RuntimeException class.
          </p>
        </li>
      </ul>
      <p>We can define our own Exception class as below:</p>
      <pre class="prettyprint">
class MyException extends Exception{
}
</pre
      >
      <p>
        You just need to extend the Exception class to create your own Exception
        class. These are considered to be checked exceptions. The following
        InsufficientFundsException class is a user-defined exception that
        extends the Exception class, making it a checked exception. An exception
        class is like any other class, containing useful fields and methods.
      </p>
      <h2>Example:</h2>
      <pre class="prettyprint">
// File Name InsufficientFundsException.java
import java.io.*;

public class InsufficientFundsException extends Exception
{
   private double amount;
   public InsufficientFundsException(double amount)
   {
      this.amount = amount;
   } 
   public double getAmount()
   {
      return amount;
   }
}
</pre
      >
      <p>
        To demonstrate using our user-defined exception, the following
        CheckingAccount class contains a withdraw() method that throws an
        InsufficientFundsException.
      </p>
      <pre class="prettyprint">
// File Name CheckingAccount.java
import java.io.*;

public class CheckingAccount
{
   private double balance;
   private int number;
   public CheckingAccount(int number)
   {
      this.number = number;
   }
   public void deposit(double amount)
   {
      balance += amount;
   }
   public void withdraw(double amount) throws
                              InsufficientFundsException
   {
      if(amount &lt;= balance)
      {
         balance -= amount;
      }
      else
      {
         double needs = amount - balance;
         throw new InsufficientFundsException(needs);
      }
   }
   public double getBalance()
   {
      return balance;
   }
   public int getNumber()
   {
      return number;
   }
}
</pre
      >
      <p>
        The following BankDemo program demonstrates invoking the deposit() and
        withdraw() methods of CheckingAccount.
      </p>
      <pre class="prettyprint">
// File Name BankDemo.java
public class BankDemo
{
   public static void main(String [] args)
   {
      CheckingAccount c = new CheckingAccount(101);
      System.out.println("Depositing $500...");
      c.deposit(500.00);
      try
      {
         System.out.println("\nWithdrawing $100...");
         c.withdraw(100.00);
         System.out.println("\nWithdrawing $600...");
         c.withdraw(600.00);
      }catch(InsufficientFundsException e)
      {
         System.out.println("Sorry, but you are short $"
                                  + e.getAmount());
         e.printStackTrace();
      }
    }
}
</pre
      >
      <p>
        Compile all the above three files and run BankDemo, this would produce
        following result:
      </p>
      <pre class="prettyprint">
Depositing $500...

Withdrawing $100...

Withdrawing $600...
Sorry, but you are short $200.0
InsufficientFundsException
        at CheckingAccount.withdraw(CheckingAccount.java:25)
        at BankDemo.main(BankDemo.java:13)
</pre
      >
      <h2>Common Exceptions:</h2>
      <p>
        In java it is possible to define two catergories of Exceptions and
        Errors.
      </p>
      <ul class="list">
        <li>
          <p>
            <b>JVM Exceptions:</b> - These are exceptions/errors that are
            exclusively or logically thrown by the JVM. Examples :
            NullPointerException, ArrayIndexOutOfBoundsException,
            ClassCastException,
          </p>
        </li>
        <li>
          <p>
            <b>Programmatic exceptions</b> . These exceptions are thrown
            explicitly by the application or the API programmers Examples:
            IllegalArgumentException, IllegalStateException.
          </p>
        </li>
      </ul>
      <br />
      <hr />
      <div class="pre-btn">
        <a href="/java/java_files_io.htm">Previous Page</a>
      </div>
      <div class="print-btn">
        <a href="/cgi-bin/printpage.cgi" target="_blank">Print Version</a>
      </div>
      <div class="pdf-btn">
        <a
          href="/java/pdf/java_exceptions.pdf"
          alt="Java - Exceptions Handling"
          target="_blank"
          >PDF Version</a
        >
      </div>
      <div class="nxt-btn">
        <a href="/java/java_inheritance.htm">Next Page</a>
      </div>
      <div class="clearer"></div>
      <hr />
    </div>
    <!-- PRINTING ENDS HERE -->
  </body>
</html>
